### PR TITLE
drop extraneous imports of part of stdlib

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by pat1** [comment]
Thanks for your contributions!

**Comment by a-detiste** [comment]
Can you please remove the need for old_div
and remove dependency on future altohether & release ?
(python3-future is being removed from Debian)

autoradio/managexmms.py:from past.utils import old_div
autoradio/autompris2.py:from past.utils import old_div
autoradio/dir2ogg.py:from past.utils import old_div
autoradio/mkplaylist.py:from past.builtins import cmp
autoradio/managempris.py:from past.utils import old_div
autoradio/autoplayer/playlist.py:from past.utils import old_div
autoradio/autoplayer/player.py:from past.utils import old_div
autoradio/autoplayer/player_gstreamer0.py:from past.utils import old_div
autoradio/manageaudacious.py:from past.utils import old_div
autoradio/autoradio_core.py:from past.utils import old_div
autoplayergui:from past.utils import old_div

**Comment by pat1** [comment]
old_div and cmp removed in aed8f9d

**Comment by a-detiste** [comment]
`__cmp__` is not used at all in Python3

**Pull request merged**
